[scope.play]
description = "Play a video file or URL"
permissions = []

[scope.control]
description = "Control video playback (pause, resume, seek, etc.)"
permissions = []

[scope.get_info]
description = "Get information about a playing video"
permissions = []

[scope.close]
description = "Close a video"
permissions = []

[scope.list_presets]
description = "List available presets"
permissions = []
